import { mapDetail, mapEvent, mapPreferences, mapRoom, mapUser } from './mapper'
import type { BootstrapRequestDto, EventDetailDto, EventSearchResponseDto, HomeFeedResponseDto, InviteContextDto, Preferences, PreferencesRequestDto, RoomIntentRequestDto, RoomSnapshotDto, RoomEventsResponseDto, SavedEventsResponseDto, SavedStateResponseDto, User, VoteResponseDto } from './types'
import { ApiError, normalizeApiError } from './errors'

export interface ApiClientOptions { baseUrl?: string; fetchImpl?: typeof fetch; getToken?: () => string | null }
let inMemoryAccessToken: string | null = null
export class ApiClient {
  private readonly baseUrl: string; private readonly fetchImpl: typeof fetch; private readonly getToken: () => string | null
  constructor(options: ApiClientOptions = {}) { this.baseUrl = options.baseUrl ?? import.meta.env.VITE_API_BASE_URL ?? '/api/v1'; this.fetchImpl = options.fetchImpl ?? globalThis.fetch.bind(globalThis); this.getToken = options.getToken ?? (() => inMemoryAccessToken) }
  private async request<T>(path: string, init: RequestInit = {}): Promise<T> {
    const headers = new Headers(init.headers); headers.set('Accept', 'application/json'); if (init.body) headers.set('Content-Type', 'application/json')
    const token = this.getToken(); if (token) headers.set('Authorization', `Bearer ${token}`)
    let response: Response
    try { response = await this.fetchImpl(`${this.baseUrl}${path}`, { ...init, headers }) } catch (error) { throw normalizeApiError(error) }
    const body = await response.json().catch(() => null)
    if (!response.ok) throw new ApiError(response.status, body ?? {}, response.headers.get('Retry-After')); return body as T
  }
  async health(): Promise<{ status: 'ready'; database: 'ready'; migrations: 'current' }> { return this.request('/health/ready') }
  async bootstrap(input: BootstrapRequestDto): Promise<{ accessToken: string; user: User; onboardingState: 'new' | 'complete'; preferences: Preferences | null; inviteContext: InviteContextDto | null }> { const x = await this.request<any>('/auth/max/bootstrap', { method: 'POST', body: JSON.stringify(input) }); inMemoryAccessToken = x.access_token; return { accessToken: x.access_token, user: mapUser(x.user), onboardingState: x.onboarding_state, preferences: x.preferences ? mapPreferences(x.preferences) : null, inviteContext: x.invite_context } }
  async replacePreferences(input: PreferencesRequestDto): Promise<Preferences> { return mapPreferences(await this.request('/me/preferences', { method: 'PUT', body: JSON.stringify(input) })) }
  async getHomeFeed(params: Record<string, string | number | undefined> = {}): Promise<Omit<HomeFeedResponseDto, 'sections' | 'active_room'> & { sections: Array<Omit<HomeFeedResponseDto['sections'][number], 'items'> & { items: ReturnType<typeof mapEvent>[] }>; activeRoom: HomeFeedResponseDto['active_room'] }> { const q = new URLSearchParams(Object.entries(params).filter(([, v]) => v !== undefined).map(([k, v]) => [k, String(v)])); const x = await this.request<HomeFeedResponseDto>(`/feed/home${q.size ? `?${q}` : ''}`); return { ...x, sections: x.sections.map((s) => ({ ...s, items: s.items.map(mapEvent) })), activeRoom: x.active_room } }
  async searchEvents(params: Record<string, string | number | boolean | string[] | undefined> = {}): Promise<{ items: ReturnType<typeof mapEvent>[]; appliedFilters: Record<string, unknown>; totalEstimate: number; nextCursor: string | null }> { const q = new URLSearchParams(); for (const [key, value] of Object.entries(params)) { if (value === undefined) continue; q.set(key, Array.isArray(value) ? value.join(',') : String(value)) }; const x = await this.request<EventSearchResponseDto>(`/events/search${q.size ? `?${q}` : ''}`); return { items: x.items.map(mapEvent), appliedFilters: x.applied_filters, totalEstimate: x.total_estimate, nextCursor: x.next_cursor } }
  async getEvent(eventId: string): Promise<ReturnType<typeof mapDetail>> { return mapDetail(await this.request<EventDetailDto>(`/events/${eventId}`)) }
  async recordBehavior(events: Array<{ client_event_id: string; type: 'impression' | 'open' | 'share'; occurred_at: string; event_id?: string | null; room_id?: string | null; metadata?: Record<string, unknown> }>): Promise<{ accepted: number; duplicates: number; rejected: number }> { return this.request('/behavior/events:batch', { method: 'POST', body: JSON.stringify({ events }) }) }
  async setSaved(eventId: string, saved: boolean): Promise<SavedStateResponseDto> { return this.request(`/me/saved-events/${encodeURIComponent(eventId)}`, { method: 'PUT', body: JSON.stringify({ saved }) }) }
  async getSaved(params: { tab?: 'saved' | 'matches'; limit?: number; cursor?: string } = {}): Promise<{ items: Array<{ event: ReturnType<typeof mapEvent>; savedAt: string | null; match: SavedEventsResponseDto['items'][number]['match'] }>; nextCursor: string | null }> { const q = new URLSearchParams(); if (params.tab) q.set('tab', params.tab); if (params.limit) q.set('limit', String(params.limit)); if (params.cursor) q.set('cursor', params.cursor); const x = await this.request<SavedEventsResponseDto>(`/me/saved-events${q.size ? `?${q}` : ''}`); return { items: x.items.map((item) => ({ event: mapEvent(item.event), savedAt: item.saved_at, match: item.match })), nextCursor: x.next_cursor } }
  async createRoom(input: { name: string; city_id: string }, idempotencyKey = crypto.randomUUID()): Promise<{ room: ReturnType<typeof mapRoom>; invite: any }> { const x = await this.request<any>('/rooms', { method: 'POST', headers: { 'Idempotency-Key': idempotencyKey }, body: JSON.stringify(input) }); return { room: mapRoom(x.room), invite: x.invite } }
  async joinRoom(token: string, idempotencyKey = crypto.randomUUID()): Promise<ReturnType<typeof mapRoom>> { return mapRoom(await this.request<RoomSnapshotDto>(`/room-invites/${encodeURIComponent(token)}/join`, { method: 'POST', headers: { 'Idempotency-Key': idempotencyKey } })) }
  async getRoom(roomId: string): Promise<ReturnType<typeof mapRoom>> { return mapRoom(await this.request<RoomSnapshotDto>(`/rooms/${roomId}`)) }
  async replaceMyIntent(roomId: string, input: RoomIntentRequestDto): Promise<ReturnType<typeof mapRoom>> { return mapRoom(await this.request<RoomSnapshotDto>(`/rooms/${roomId}/intent/me`, { method: 'PUT', body: JSON.stringify(input) })) }
  async getRoomEvents(roomId: string, params: { limit?: number; cursor?: string } = {}): Promise<RoomEventsResponseDto> { const q = new URLSearchParams(); if (params.limit) q.set('limit', String(params.limit)); if (params.cursor) q.set('cursor', params.cursor); return this.request(`/rooms/${roomId}/events${q.size ? `?${q}` : ''}`) }
  async vote(roomId: string, eventId: string, input: { pool_version: number; vote: 'like' | 'dislike' }): Promise<VoteResponseDto> { return this.request(`/rooms/${roomId}/events/${eventId}/vote`, { method: 'PUT', body: JSON.stringify(input) }) }
  async recordTicketClick(eventId: string, input: { source: string; room_id?: string | null }): Promise<{ external_url: string }> { return this.request(`/events/${eventId}/ticket-click`, { method: 'POST', body: JSON.stringify(input) }) }
}
export const apiClient = new ApiClient()
