// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BehaviorEventEntryPoint.
const (
	BehaviorEventEntryPointBot            BehaviorEventEntryPoint = "bot"
	BehaviorEventEntryPointDeepLink       BehaviorEventEntryPoint = "deep_link"
	BehaviorEventEntryPointDirect         BehaviorEventEntryPoint = "direct"
	BehaviorEventEntryPointFeed           BehaviorEventEntryPoint = "feed"
	BehaviorEventEntryPointHome           BehaviorEventEntryPoint = "home"
	BehaviorEventEntryPointLessThannil    BehaviorEventEntryPoint = "<nil>"
	BehaviorEventEntryPointMap            BehaviorEventEntryPoint = "map"
	BehaviorEventEntryPointRecommendation BehaviorEventEntryPoint = "recommendation"
	BehaviorEventEntryPointRoom           BehaviorEventEntryPoint = "room"
	BehaviorEventEntryPointRoomInvite     BehaviorEventEntryPoint = "room_invite"
	BehaviorEventEntryPointSaved          BehaviorEventEntryPoint = "saved"
	BehaviorEventEntryPointSearch         BehaviorEventEntryPoint = "search"
	BehaviorEventEntryPointSharedEvent    BehaviorEventEntryPoint = "shared_event"
	BehaviorEventEntryPointUnknown        BehaviorEventEntryPoint = "unknown"
)

// Valid indicates whether the value is a known member of the BehaviorEventEntryPoint enum.
func (e BehaviorEventEntryPoint) Valid() bool {
	switch e {
	case BehaviorEventEntryPointBot:
		return true
	case BehaviorEventEntryPointDeepLink:
		return true
	case BehaviorEventEntryPointDirect:
		return true
	case BehaviorEventEntryPointFeed:
		return true
	case BehaviorEventEntryPointHome:
		return true
	case BehaviorEventEntryPointLessThannil:
		return true
	case BehaviorEventEntryPointMap:
		return true
	case BehaviorEventEntryPointRecommendation:
		return true
	case BehaviorEventEntryPointRoom:
		return true
	case BehaviorEventEntryPointRoomInvite:
		return true
	case BehaviorEventEntryPointSaved:
		return true
	case BehaviorEventEntryPointSearch:
		return true
	case BehaviorEventEntryPointSharedEvent:
		return true
	case BehaviorEventEntryPointUnknown:
		return true
	default:
		return false
	}
}

// Defines values for BehaviorEventEventVersion.
const (
	N1 BehaviorEventEventVersion = 1
)

// Valid indicates whether the value is a known member of the BehaviorEventEventVersion enum.
func (e BehaviorEventEventVersion) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for BehaviorEventPlatform.
const (
	BehaviorEventPlatformBrowser     BehaviorEventPlatform = "browser"
	BehaviorEventPlatformLessThannil BehaviorEventPlatform = "<nil>"
	BehaviorEventPlatformMaxAndroid  BehaviorEventPlatform = "max_android"
	BehaviorEventPlatformMaxDesktop  BehaviorEventPlatform = "max_desktop"
	BehaviorEventPlatformMaxIos      BehaviorEventPlatform = "max_ios"
	BehaviorEventPlatformMaxWeb      BehaviorEventPlatform = "max_web"
	BehaviorEventPlatformUnknown     BehaviorEventPlatform = "unknown"
)

// Valid indicates whether the value is a known member of the BehaviorEventPlatform enum.
func (e BehaviorEventPlatform) Valid() bool {
	switch e {
	case BehaviorEventPlatformBrowser:
		return true
	case BehaviorEventPlatformLessThannil:
		return true
	case BehaviorEventPlatformMaxAndroid:
		return true
	case BehaviorEventPlatformMaxDesktop:
		return true
	case BehaviorEventPlatformMaxIos:
		return true
	case BehaviorEventPlatformMaxWeb:
		return true
	case BehaviorEventPlatformUnknown:
		return true
	default:
		return false
	}
}

// Defines values for BehaviorEventType.
const (
	AppOpened            BehaviorEventType = "app_opened"
	ClientError          BehaviorEventType = "client_error"
	ClientPerformance    BehaviorEventType = "client_performance"
	EventImpression      BehaviorEventType = "event_impression"
	EventOpened          BehaviorEventType = "event_opened"
	EventSwipeImpression BehaviorEventType = "event_swipe_impression"
	FeedOpened           BehaviorEventType = "feed_opened"
	FiltersApplied       BehaviorEventType = "filters_applied"
	FiltersOpened        BehaviorEventType = "filters_opened"
	FiltersReset         BehaviorEventType = "filters_reset"
	Impression           BehaviorEventType = "impression"
	InviteLinkOpened     BehaviorEventType = "invite_link_opened"
	InviteOpened         BehaviorEventType = "invite_opened"
	InviteShareFailed    BehaviorEventType = "invite_share_failed"
	InviteShared         BehaviorEventType = "invite_shared"
	MapMarkerOpened      BehaviorEventType = "map_marker_opened"
	MapOpened            BehaviorEventType = "map_opened"
	MatchOpened          BehaviorEventType = "match_opened"
	MatchShown           BehaviorEventType = "match_shown"
	OnboardingCompleted  BehaviorEventType = "onboarding_completed"
	OnboardingStarted    BehaviorEventType = "onboarding_started"
	Open                 BehaviorEventType = "open"
	RoomCreationFailed   BehaviorEventType = "room_creation_failed"
	RoomCreationStarted  BehaviorEventType = "room_creation_started"
	RoomJoinFailed       BehaviorEventType = "room_join_failed"
	RoomJoinStarted      BehaviorEventType = "room_join_started"
	RoomOpened           BehaviorEventType = "room_opened"
	SearchPerformed      BehaviorEventType = "search_performed"
	SessionStarted       BehaviorEventType = "session_started"
	Share                BehaviorEventType = "share"
	SwipePoolExhausted   BehaviorEventType = "swipe_pool_exhausted"
	SwipeSessionStarted  BehaviorEventType = "swipe_session_started"
	TicketRedirectFailed BehaviorEventType = "ticket_redirect_failed"
)

// Valid indicates whether the value is a known member of the BehaviorEventType enum.
func (e BehaviorEventType) Valid() bool {
	switch e {
	case AppOpened:
		return true
	case ClientError:
		return true
	case ClientPerformance:
		return true
	case EventImpression:
		return true
	case EventOpened:
		return true
	case EventSwipeImpression:
		return true
	case FeedOpened:
		return true
	case FiltersApplied:
		return true
	case FiltersOpened:
		return true
	case FiltersReset:
		return true
	case Impression:
		return true
	case InviteLinkOpened:
		return true
	case InviteOpened:
		return true
	case InviteShareFailed:
		return true
	case InviteShared:
		return true
	case MapMarkerOpened:
		return true
	case MapOpened:
		return true
	case MatchOpened:
		return true
	case MatchShown:
		return true
	case OnboardingCompleted:
		return true
	case OnboardingStarted:
		return true
	case Open:
		return true
	case RoomCreationFailed:
		return true
	case RoomCreationStarted:
		return true
	case RoomJoinFailed:
		return true
	case RoomJoinStarted:
		return true
	case RoomOpened:
		return true
	case SearchPerformed:
		return true
	case SessionStarted:
		return true
	case Share:
		return true
	case SwipePoolExhausted:
		return true
	case SwipeSessionStarted:
		return true
	case TicketRedirectFailed:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapResponseOnboardingState.
const (
	Complete BootstrapResponseOnboardingState = "complete"
	New      BootstrapResponseOnboardingState = "new"
)

// Valid indicates whether the value is a known member of the BootstrapResponseOnboardingState enum.
func (e BootstrapResponseOnboardingState) Valid() bool {
	switch e {
	case Complete:
		return true
	case New:
		return true
	default:
		return false
	}
}

// Defines values for BootstrapResponseTokenType.
const (
	Bearer BootstrapResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the BootstrapResponseTokenType enum.
func (e BootstrapResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for CategorySlug.
const (
	Cinema      CategorySlug = "cinema"
	Concerts    CategorySlug = "concerts"
	Exhibitions CategorySlug = "exhibitions"
	Festivals   CategorySlug = "festivals"
	Food        CategorySlug = "food"
	Other       CategorySlug = "other"
	Parties     CategorySlug = "parties"
	Sports      CategorySlug = "sports"
	Standup     CategorySlug = "standup"
	Theatre     CategorySlug = "theatre"
	Walks       CategorySlug = "walks"
)

// Valid indicates whether the value is a known member of the CategorySlug enum.
func (e CategorySlug) Valid() bool {
	switch e {
	case Cinema:
		return true
	case Concerts:
		return true
	case Exhibitions:
		return true
	case Festivals:
		return true
	case Food:
		return true
	case Other:
		return true
	case Parties:
		return true
	case Sports:
		return true
	case Standup:
		return true
	case Theatre:
		return true
	case Walks:
		return true
	default:
		return false
	}
}

// Defines values for DayType.
const (
	Weekday DayType = "weekday"
	Weekend DayType = "weekend"
)

// Valid indicates whether the value is a known member of the DayType enum.
func (e DayType) Valid() bool {
	switch e {
	case Weekday:
		return true
	case Weekend:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseErrorCode.
const (
	ACTIVEROOMEXISTS    ErrorResponseErrorCode = "ACTIVE_ROOM_EXISTS"
	ALREADYMATCHED      ErrorResponseErrorCode = "ALREADY_MATCHED"
	CONFLICT            ErrorResponseErrorCode = "CONFLICT"
	EVENTUNAVAILABLE    ErrorResponseErrorCode = "EVENT_UNAVAILABLE"
	FORBIDDEN           ErrorResponseErrorCode = "FORBIDDEN"
	IDEMPOTENCYCONFLICT ErrorResponseErrorCode = "IDEMPOTENCY_CONFLICT"
	INTENTLOCKED        ErrorResponseErrorCode = "INTENT_LOCKED"
	INTERNAL            ErrorResponseErrorCode = "INTERNAL"
	INVITEEXPIRED       ErrorResponseErrorCode = "INVITE_EXPIRED"
	NOTFOUND            ErrorResponseErrorCode = "NOT_FOUND"
	POOLEXHAUSTED       ErrorResponseErrorCode = "POOL_EXHAUSTED"
	POOLNOTREADY        ErrorResponseErrorCode = "POOL_NOT_READY"
	RATELIMITED         ErrorResponseErrorCode = "RATE_LIMITED"
	ROOMEXPIRED         ErrorResponseErrorCode = "ROOM_EXPIRED"
	ROOMFULL            ErrorResponseErrorCode = "ROOM_FULL"
	ROOMNOTREADY        ErrorResponseErrorCode = "ROOM_NOT_READY"
	ROUNDLIMITREACHED   ErrorResponseErrorCode = "ROUND_LIMIT_REACHED"
	STALEPOOLVERSION    ErrorResponseErrorCode = "STALE_POOL_VERSION"
	TICKETSUNAVAILABLE  ErrorResponseErrorCode = "TICKETS_UNAVAILABLE"
	TOKENEXPIRED        ErrorResponseErrorCode = "TOKEN_EXPIRED"
	UNAUTHENTICATED     ErrorResponseErrorCode = "UNAUTHENTICATED"
	VALIDATIONFAILED    ErrorResponseErrorCode = "VALIDATION_FAILED"
	VOTEALREADYCAST     ErrorResponseErrorCode = "VOTE_ALREADY_CAST"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case ACTIVEROOMEXISTS:
		return true
	case ALREADYMATCHED:
		return true
	case CONFLICT:
		return true
	case EVENTUNAVAILABLE:
		return true
	case FORBIDDEN:
		return true
	case IDEMPOTENCYCONFLICT:
		return true
	case INTENTLOCKED:
		return true
	case INTERNAL:
		return true
	case INVITEEXPIRED:
		return true
	case NOTFOUND:
		return true
	case POOLEXHAUSTED:
		return true
	case POOLNOTREADY:
		return true
	case RATELIMITED:
		return true
	case ROOMEXPIRED:
		return true
	case ROOMFULL:
		return true
	case ROOMNOTREADY:
		return true
	case ROUNDLIMITREACHED:
		return true
	case STALEPOOLVERSION:
		return true
	case TICKETSUNAVAILABLE:
		return true
	case TOKENEXPIRED:
		return true
	case UNAUTHENTICATED:
		return true
	case VALIDATIONFAILED:
		return true
	case VOTEALREADYCAST:
		return true
	default:
		return false
	}
}

// Defines values for EventCardCurrency.
const (
	EventCardCurrencyRUB EventCardCurrency = "RUB"
)

// Valid indicates whether the value is a known member of the EventCardCurrency enum.
func (e EventCardCurrency) Valid() bool {
	switch e {
	case EventCardCurrencyRUB:
		return true
	default:
		return false
	}
}

// Defines values for EventDetailAgeRating.
const (
	EventDetailAgeRatingLessThannil EventDetailAgeRating = "<nil>"
	EventDetailAgeRatingN0          EventDetailAgeRating = "0+"
	EventDetailAgeRatingN12         EventDetailAgeRating = "12+"
	EventDetailAgeRatingN16         EventDetailAgeRating = "16+"
	EventDetailAgeRatingN18         EventDetailAgeRating = "18+"
	EventDetailAgeRatingN6          EventDetailAgeRating = "6+"
	EventDetailAgeRatingUnknown     EventDetailAgeRating = "unknown"
)

// Valid indicates whether the value is a known member of the EventDetailAgeRating enum.
func (e EventDetailAgeRating) Valid() bool {
	switch e {
	case EventDetailAgeRatingLessThannil:
		return true
	case EventDetailAgeRatingN0:
		return true
	case EventDetailAgeRatingN12:
		return true
	case EventDetailAgeRatingN16:
		return true
	case EventDetailAgeRatingN18:
		return true
	case EventDetailAgeRatingN6:
		return true
	case EventDetailAgeRatingUnknown:
		return true
	default:
		return false
	}
}

// Defines values for EventDetailCurrency.
const (
	EventDetailCurrencyRUB EventDetailCurrency = "RUB"
)

// Valid indicates whether the value is a known member of the EventDetailCurrency enum.
func (e EventDetailCurrency) Valid() bool {
	switch e {
	case EventDetailCurrencyRUB:
		return true
	default:
		return false
	}
}

// Defines values for EventDetailStatus.
const (
	Cancelled EventDetailStatus = "cancelled"
	Published EventDetailStatus = "published"
	SoldOut   EventDetailStatus = "sold_out"
)

// Valid indicates whether the value is a known member of the EventDetailStatus enum.
func (e EventDetailStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Published:
		return true
	case SoldOut:
		return true
	default:
		return false
	}
}

// Defines values for EventImageRole.
const (
	EventImageRoleCard    EventImageRole = "card"
	EventImageRoleGallery EventImageRole = "gallery"
	EventImageRoleHero    EventImageRole = "hero"
)

// Valid indicates whether the value is a known member of the EventImageRole enum.
func (e EventImageRole) Valid() bool {
	switch e {
	case EventImageRoleCard:
		return true
	case EventImageRoleGallery:
		return true
	case EventImageRoleHero:
		return true
	default:
		return false
	}
}

// Defines values for EventMapClusterKind.
const (
	Cluster EventMapClusterKind = "cluster"
)

// Valid indicates whether the value is a known member of the EventMapClusterKind enum.
func (e EventMapClusterKind) Valid() bool {
	switch e {
	case Cluster:
		return true
	default:
		return false
	}
}

// Defines values for EventMapPointKind.
const (
	Event EventMapPointKind = "event"
)

// Valid indicates whether the value is a known member of the EventMapPointKind enum.
func (e EventMapPointKind) Valid() bool {
	switch e {
	case Event:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseDatabase.
const (
	HealthResponseDatabaseReady HealthResponseDatabase = "ready"
)

// Valid indicates whether the value is a known member of the HealthResponseDatabase enum.
func (e HealthResponseDatabase) Valid() bool {
	switch e {
	case HealthResponseDatabaseReady:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseMigrations.
const (
	Current HealthResponseMigrations = "current"
)

// Valid indicates whether the value is a known member of the HealthResponseMigrations enum.
func (e HealthResponseMigrations) Valid() bool {
	switch e {
	case Current:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusReady HealthResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for HomeFeedResponseSectionsType.
const (
	HomeFeedResponseSectionsTypeForYou  HomeFeedResponseSectionsType = "for_you"
	HomeFeedResponseSectionsTypeHero    HomeFeedResponseSectionsType = "hero"
	HomeFeedResponseSectionsTypeNearby  HomeFeedResponseSectionsType = "nearby"
	HomeFeedResponseSectionsTypePopular HomeFeedResponseSectionsType = "popular"
)

// Valid indicates whether the value is a known member of the HomeFeedResponseSectionsType enum.
func (e HomeFeedResponseSectionsType) Valid() bool {
	switch e {
	case HomeFeedResponseSectionsTypeForYou:
		return true
	case HomeFeedResponseSectionsTypeHero:
		return true
	case HomeFeedResponseSectionsTypeNearby:
		return true
	case HomeFeedResponseSectionsTypePopular:
		return true
	default:
		return false
	}
}

// Defines values for InviteContextStatus.
const (
	Expired  InviteContextStatus = "expired"
	Full     InviteContextStatus = "full"
	Joinable InviteContextStatus = "joinable"
)

// Valid indicates whether the value is a known member of the InviteContextStatus enum.
func (e InviteContextStatus) Valid() bool {
	switch e {
	case Expired:
		return true
	case Full:
		return true
	case Joinable:
		return true
	default:
		return false
	}
}

// Defines values for MyIntentExclusionSlugs.
const (
	MyIntentExclusionSlugsFarFromMetro MyIntentExclusionSlugs = "far_from_metro"
	MyIntentExclusionSlugsNightclubs   MyIntentExclusionSlugs = "nightclubs"
	MyIntentExclusionSlugsOutdoor      MyIntentExclusionSlugs = "outdoor"
	MyIntentExclusionSlugsVeryLoud     MyIntentExclusionSlugs = "very_loud"
)

// Valid indicates whether the value is a known member of the MyIntentExclusionSlugs enum.
func (e MyIntentExclusionSlugs) Valid() bool {
	switch e {
	case MyIntentExclusionSlugsFarFromMetro:
		return true
	case MyIntentExclusionSlugsNightclubs:
		return true
	case MyIntentExclusionSlugsOutdoor:
		return true
	case MyIntentExclusionSlugsVeryLoud:
		return true
	default:
		return false
	}
}

// Defines values for PoolSummaryExhaustionReasonsCode.
const (
	Budget          PoolSummaryExhaustionReasonsCode = "budget"
	CatalogShortage PoolSummaryExhaustionReasonsCode = "catalog_shortage"
	Categories      PoolSummaryExhaustionReasonsCode = "categories"
	Date            PoolSummaryExhaustionReasonsCode = "date"
	Radius          PoolSummaryExhaustionReasonsCode = "radius"
)

// Valid indicates whether the value is a known member of the PoolSummaryExhaustionReasonsCode enum.
func (e PoolSummaryExhaustionReasonsCode) Valid() bool {
	switch e {
	case Budget:
		return true
	case CatalogShortage:
		return true
	case Categories:
		return true
	case Date:
		return true
	case Radius:
		return true
	default:
		return false
	}
}

// Defines values for PoolSummaryState.
const (
	PoolSummaryStateExhausted PoolSummaryState = "exhausted"
	PoolSummaryStateRanking   PoolSummaryState = "ranking"
	PoolSummaryStateReady     PoolSummaryState = "ready"
)

// Valid indicates whether the value is a known member of the PoolSummaryState enum.
func (e PoolSummaryState) Valid() bool {
	switch e {
	case PoolSummaryStateExhausted:
		return true
	case PoolSummaryStateRanking:
		return true
	case PoolSummaryStateReady:
		return true
	default:
		return false
	}
}

// Defines values for PublicParticipantRole.
const (
	Creator     PublicParticipantRole = "creator"
	Participant PublicParticipantRole = "participant"
)

// Valid indicates whether the value is a known member of the PublicParticipantRole enum.
func (e PublicParticipantRole) Valid() bool {
	switch e {
	case Creator:
		return true
	case Participant:
		return true
	default:
		return false
	}
}

// Defines values for RecommendationReasonCode.
const (
	RecommendationReasonCodeBudgetFit       RecommendationReasonCode = "budget_fit"
	RecommendationReasonCodeNearby          RecommendationReasonCode = "nearby"
	RecommendationReasonCodePopular         RecommendationReasonCode = "popular"
	RecommendationReasonCodeProfileAffinity RecommendationReasonCode = "profile_affinity"
	RecommendationReasonCodeSharedCategory  RecommendationReasonCode = "shared_category"
	RecommendationReasonCodeTimeFit         RecommendationReasonCode = "time_fit"
)

// Valid indicates whether the value is a known member of the RecommendationReasonCode enum.
func (e RecommendationReasonCode) Valid() bool {
	switch e {
	case RecommendationReasonCodeBudgetFit:
		return true
	case RecommendationReasonCodeNearby:
		return true
	case RecommendationReasonCodePopular:
		return true
	case RecommendationReasonCodeProfileAffinity:
		return true
	case RecommendationReasonCodeSharedCategory:
		return true
	case RecommendationReasonCodeTimeFit:
		return true
	default:
		return false
	}
}

// Defines values for RoomIntentRequestExclusionSlugs.
const (
	RoomIntentRequestExclusionSlugsFarFromMetro RoomIntentRequestExclusionSlugs = "far_from_metro"
	RoomIntentRequestExclusionSlugsNightclubs   RoomIntentRequestExclusionSlugs = "nightclubs"
	RoomIntentRequestExclusionSlugsOutdoor      RoomIntentRequestExclusionSlugs = "outdoor"
	RoomIntentRequestExclusionSlugsVeryLoud     RoomIntentRequestExclusionSlugs = "very_loud"
)

// Valid indicates whether the value is a known member of the RoomIntentRequestExclusionSlugs enum.
func (e RoomIntentRequestExclusionSlugs) Valid() bool {
	switch e {
	case RoomIntentRequestExclusionSlugsFarFromMetro:
		return true
	case RoomIntentRequestExclusionSlugsNightclubs:
		return true
	case RoomIntentRequestExclusionSlugsOutdoor:
		return true
	case RoomIntentRequestExclusionSlugsVeryLoud:
		return true
	default:
		return false
	}
}

// Defines values for RoomSnapshotAllowedActions.
const (
	EditIntent           RoomSnapshotAllowedActions = "edit_intent"
	Invite               RoomSnapshotAllowedActions = "invite"
	Join                 RoomSnapshotAllowedActions = "join"
	RestartWithNewIntent RoomSnapshotAllowedActions = "restart_with_new_intent"
	ViewMatch            RoomSnapshotAllowedActions = "view_match"
	ViewPool             RoomSnapshotAllowedActions = "view_pool"
	Vote                 RoomSnapshotAllowedActions = "vote"
	Wait                 RoomSnapshotAllowedActions = "wait"
)

// Valid indicates whether the value is a known member of the RoomSnapshotAllowedActions enum.
func (e RoomSnapshotAllowedActions) Valid() bool {
	switch e {
	case EditIntent:
		return true
	case Invite:
		return true
	case Join:
		return true
	case RestartWithNewIntent:
		return true
	case ViewMatch:
		return true
	case ViewPool:
		return true
	case Vote:
		return true
	case Wait:
		return true
	default:
		return false
	}
}

// Defines values for RoomState.
const (
	RoomStateCollectingIntents RoomState = "collecting_intents"
	RoomStateExhausted         RoomState = "exhausted"
	RoomStateMatched           RoomState = "matched"
	RoomStateRanking           RoomState = "ranking"
	RoomStateVoting            RoomState = "voting"
)

// Valid indicates whether the value is a known member of the RoomState enum.
func (e RoomState) Valid() bool {
	switch e {
	case RoomStateCollectingIntents:
		return true
	case RoomStateExhausted:
		return true
	case RoomStateMatched:
		return true
	case RoomStateRanking:
		return true
	case RoomStateVoting:
		return true
	default:
		return false
	}
}

// Defines values for TicketClickRequestSource.
const (
	TicketClickRequestSourceEventDetail TicketClickRequestSource = "event_detail"
	TicketClickRequestSourceFeed        TicketClickRequestSource = "feed"
	TicketClickRequestSourceMatch       TicketClickRequestSource = "match"
	TicketClickRequestSourceSaved       TicketClickRequestSource = "saved"
)

// Valid indicates whether the value is a known member of the TicketClickRequestSource enum.
func (e TicketClickRequestSource) Valid() bool {
	switch e {
	case TicketClickRequestSourceEventDetail:
		return true
	case TicketClickRequestSourceFeed:
		return true
	case TicketClickRequestSourceMatch:
		return true
	case TicketClickRequestSourceSaved:
		return true
	default:
		return false
	}
}

// Defines values for TimeSlot.
const (
	Day     TimeSlot = "day"
	Evening TimeSlot = "evening"
	Morning TimeSlot = "morning"
	Night   TimeSlot = "night"
)

// Valid indicates whether the value is a known member of the TimeSlot enum.
func (e TimeSlot) Valid() bool {
	switch e {
	case Day:
		return true
	case Evening:
		return true
	case Morning:
		return true
	case Night:
		return true
	default:
		return false
	}
}

// Defines values for VoteValue.
const (
	Dislike VoteValue = "dislike"
	Like    VoteValue = "like"
)

// Valid indicates whether the value is a known member of the VoteValue enum.
func (e VoteValue) Valid() bool {
	switch e {
	case Dislike:
		return true
	case Like:
		return true
	default:
		return false
	}
}

// Defines values for GetInternalAnalyticsDashboardParamsDays.
const (
	N30 GetInternalAnalyticsDashboardParamsDays = 30
	N7  GetInternalAnalyticsDashboardParamsDays = 7
	N90 GetInternalAnalyticsDashboardParamsDays = 90
)

// Valid indicates whether the value is a known member of the GetInternalAnalyticsDashboardParamsDays enum.
func (e GetInternalAnalyticsDashboardParamsDays) Valid() bool {
	switch e {
	case N30:
		return true
	case N7:
		return true
	case N90:
		return true
	default:
		return false
	}
}

// Defines values for GetMySavedEventsParamsTab.
const (
	GetMySavedEventsParamsTabMatches GetMySavedEventsParamsTab = "matches"
	GetMySavedEventsParamsTabSaved   GetMySavedEventsParamsTab = "saved"
)

// Valid indicates whether the value is a known member of the GetMySavedEventsParamsTab enum.
func (e GetMySavedEventsParamsTab) Valid() bool {
	switch e {
	case GetMySavedEventsParamsTabMatches:
		return true
	case GetMySavedEventsParamsTabSaved:
		return true
	default:
		return false
	}
}

// BehaviorBatchRequest defines model for BehaviorBatchRequest.
type BehaviorBatchRequest struct {
	Events []BehaviorEvent `json:"events"`
}

// BehaviorBatchResponse defines model for BehaviorBatchResponse.
type BehaviorBatchResponse struct {
	Accepted   int `json:"accepted"`
	Duplicates int `json:"duplicates"`
	Rejected   int `json:"rejected"`
}

// BehaviorEvent defines model for BehaviorEvent.
type BehaviorEvent struct {
	AppVersion    nullable.Nullable[string]                  `json:"app_version,omitempty"`
	ClientEventId string                                     `json:"client_event_id"`
	EntryPoint    nullable.Nullable[BehaviorEventEntryPoint] `json:"entry_point,omitempty"`
	EventId       nullable.Nullable[openapi_types.UUID]      `json:"event_id,omitempty"`
	EventVersion  BehaviorEventEventVersion                  `json:"event_version"`

	// Metadata Только whitelisted metadata. PII, raw URLs, MAX init data, координаты и свободный текст запрещены.
	Metadata   *BehaviorMetadata                        `json:"metadata,omitempty"`
	OccurredAt time.Time                                `json:"occurred_at"`
	Platform   nullable.Nullable[BehaviorEventPlatform] `json:"platform,omitempty"`

	// Properties Whitelisted non-PII event properties. Raw search text, precise coordinates and secrets are prohibited.
	Properties *map[string]interface{}               `json:"properties,omitempty"`
	RoomId     nullable.Nullable[openapi_types.UUID] `json:"room_id,omitempty"`
	SessionId  nullable.Nullable[openapi_types.UUID] `json:"session_id,omitempty"`
	Type       BehaviorEventType                     `json:"type"`
}

// BehaviorEventEntryPoint defines model for BehaviorEvent.EntryPoint.
type BehaviorEventEntryPoint string

// BehaviorEventEventVersion defines model for BehaviorEvent.EventVersion.
type BehaviorEventEventVersion int

// BehaviorEventPlatform defines model for BehaviorEvent.Platform.
type BehaviorEventPlatform string

// BehaviorEventType defines model for BehaviorEvent.Type.
type BehaviorEventType string

// BehaviorMetadata Только whitelisted metadata. PII, raw URLs, MAX init data, координаты и свободный текст запрещены.
type BehaviorMetadata struct {
	Position  *int    `json:"position,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
	Surface   *string `json:"surface,omitempty"`
}

// BootstrapRequest defines model for BootstrapRequest.
type BootstrapRequest struct {
	InitData string `json:"init_data"`

	// StartParam Необязательный client hint; backend не доверяет ему без совпадения с start_param из проверенного init_data
	StartParam nullable.Nullable[string] `json:"start_param,omitempty"`
}

// BootstrapResponse defines model for BootstrapResponse.
type BootstrapResponse struct {
	AccessToken     string                                 `json:"access_token"`
	ExpiresIn       int                                    `json:"expires_in"`
	InviteContext   nullable.Nullable[InviteContext]       `json:"invite_context"`
	OnboardingState BootstrapResponseOnboardingState       `json:"onboarding_state"`
	Preferences     nullable.Nullable[PreferencesResponse] `json:"preferences"`
	TokenType       BootstrapResponseTokenType             `json:"token_type"`
	User            User                                   `json:"user"`
}

// BootstrapResponseOnboardingState defines model for BootstrapResponse.OnboardingState.
type BootstrapResponseOnboardingState string

// BootstrapResponseTokenType defines model for BootstrapResponse.TokenType.
type BootstrapResponseTokenType string

// CategorySlug defines model for CategorySlug.
type CategorySlug string

// CreateRoomRequest defines model for CreateRoomRequest.
type CreateRoomRequest struct {
	CityId openapi_types.UUID `json:"city_id"`
	Name   string             `json:"name"`
}

// CreateRoomResponse defines model for CreateRoomResponse.
type CreateRoomResponse struct {
	Invite struct {
		ExpiresAt   time.Time `json:"expires_at"`
		MaxDeepLink string    `json:"max_deep_link"`

		// Token Возвращается только при создании
		Token string `json:"token"`
		Url   string `json:"url"`
	} `json:"invite"`
	Room RoomSnapshot `json:"room"`
}

// DataProvenance defines model for DataProvenance.
type DataProvenance struct {
	// IsDemo true означает тестовые или подготовленные данные, а не реальную интеграцию
	IsDemo bool `json:"is_demo"`

	// Source Источник каталожной записи; demo для подготовленных данных
	Source          string                       `json:"source"`
	SourceUpdatedAt nullable.Nullable[time.Time] `json:"source_updated_at,omitempty"`
}

// DayType defines model for DayType.
type DayType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code      ErrorResponseErrorCode       `json:"code"`
		Details   *ErrorResponse_Error_Details `json:"details,omitempty"`
		Message   string                       `json:"message"`
		RequestId string                       `json:"request_id"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// ErrorResponse_Error_Details defines model for ErrorResponse.Error.Details.
type ErrorResponse_Error_Details struct {
	ActiveRoom         nullable.Nullable[RoomSummary] `json:"active_room,omitempty"`
	CurrentPoolVersion *int                           `json:"current_pool_version,omitempty"`
	Field              *string                        `json:"field,omitempty"`
	Fields             *[]struct {
		Field  string `json:"field"`
		Reason string `json:"reason"`
	} `json:"fields,omitempty"`
	Match                nullable.Nullable[MatchSummary] `json:"match,omitempty"`
	MyPoolFinished       *bool                           `json:"my_pool_finished,omitempty"`
	RoomExhausted        *bool                           `json:"room_exhausted,omitempty"`
	AdditionalProperties map[string]interface{}          `json:"-"`
}

// EventCard defines model for EventCard.
type EventCard struct {
	CategorySlug  CategorySlug               `json:"category_slug"`
	Currency      EventCardCurrency          `json:"currency"`
	DateLabel     string                     `json:"date_label"`
	DistanceLabel nullable.Nullable[string]  `json:"distance_label,omitempty"`
	DistanceM     nullable.Nullable[int]     `json:"distance_m,omitempty"`
	Id            openapi_types.UUID         `json:"id"`
	ImageUrl      nullable.Nullable[string]  `json:"image_url"`
	Latitude      nullable.Nullable[float64] `json:"latitude,omitempty"`
	Longitude     nullable.Nullable[float64] `json:"longitude,omitempty"`

	// OtherOccurrencesCount Количество других подходящих будущих сеансов этого же мероприятия.
	OtherOccurrencesCount *int                      `json:"other_occurrences_count,omitempty"`
	PriceFromMinor        nullable.Nullable[int]    `json:"price_from_minor"`
	PriceLabel            string                    `json:"price_label"`
	Reasons               []RecommendationReason    `json:"reasons"`
	Saved                 bool                      `json:"saved"`
	StartsAt              time.Time                 `json:"starts_at"`
	Subtitle              nullable.Nullable[string] `json:"subtitle,omitempty"`
	Timezone              string                    `json:"timezone"`
	Title                 string                    `json:"title"`
	VenueName             string                    `json:"venue_name"`
}

// EventCardCurrency defines model for EventCard.Currency.
type EventCardCurrency string

// EventDetail defines model for EventDetail.
type EventDetail struct {
	AgeRating      nullable.Nullable[EventDetailAgeRating] `json:"age_rating,omitempty"`
	CategorySlug   CategorySlug                            `json:"category_slug"`
	Currency       EventDetailCurrency                     `json:"currency"`
	DataProvenance DataProvenance                          `json:"data_provenance"`
	DateLabel      string                                  `json:"date_label"`
	Description    string                                  `json:"description"`
	DistanceLabel  nullable.Nullable[string]               `json:"distance_label,omitempty"`
	DistanceM      nullable.Nullable[int]                  `json:"distance_m,omitempty"`
	EndsAt         nullable.Nullable[time.Time]            `json:"ends_at,omitempty"`
	Id             openapi_types.UUID                      `json:"id"`
	ImageUrl       nullable.Nullable[string]               `json:"image_url"`
	Images         []EventImage                            `json:"images"`
	Latitude       nullable.Nullable[float64]              `json:"latitude,omitempty"`
	Longitude      nullable.Nullable[float64]              `json:"longitude,omitempty"`

	// OtherOccurrencesCount Количество других подходящих будущих сеансов этого же мероприятия.
	OtherOccurrencesCount *int                      `json:"other_occurrences_count,omitempty"`
	PriceFromMinor        nullable.Nullable[int]    `json:"price_from_minor"`
	PriceLabel            string                    `json:"price_label"`
	Reasons               []RecommendationReason    `json:"reasons"`
	Saved                 bool                      `json:"saved"`
	StartsAt              time.Time                 `json:"starts_at"`
	Status                EventDetailStatus         `json:"status"`
	Subtitle              nullable.Nullable[string] `json:"subtitle,omitempty"`
	TicketAvailable       bool                      `json:"ticket_available"`
	Timezone              string                    `json:"timezone"`
	Title                 string                    `json:"title"`
	Venue                 Venue                     `json:"venue"`
	VenueName             string                    `json:"venue_name"`
}

// EventDetailAgeRating defines model for EventDetail.AgeRating.
type EventDetailAgeRating string

// EventDetailCurrency defines model for EventDetail.Currency.
type EventDetailCurrency string

// EventDetailStatus defines model for EventDetail.Status.
type EventDetailStatus string

// EventImage defines model for EventImage.
type EventImage struct {
	Height nullable.Nullable[int] `json:"height,omitempty"`
	Role   EventImageRole         `json:"role"`
	Url    string                 `json:"url"`
	Width  nullable.Nullable[int] `json:"width,omitempty"`
}

// EventImageRole defines model for EventImage.Role.
type EventImageRole string

// EventMapCluster defines model for EventMapCluster.
type EventMapCluster struct {
	Count     int                 `json:"count"`
	East      float64             `json:"east"`
	Id        string              `json:"id"`
	Kind      EventMapClusterKind `json:"kind"`
	Latitude  float64             `json:"latitude"`
	Longitude float64             `json:"longitude"`
	Members   []EventMapPoint     `json:"members"`
	North     float64             `json:"north"`
	South     float64             `json:"south"`
	West      float64             `json:"west"`
}

// EventMapClusterKind defines model for EventMapCluster.Kind.
type EventMapClusterKind string

// EventMapPoint defines model for EventMapPoint.
type EventMapPoint struct {
	Event     EventCard          `json:"event"`
	Id        openapi_types.UUID `json:"id"`
	Kind      EventMapPointKind  `json:"kind"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
}

// EventMapPointKind defines model for EventMapPoint.Kind.
type EventMapPointKind string

// EventMapResponse defines model for EventMapResponse.
type EventMapResponse struct {
	Items []EventMapResponse_Items_Item `json:"items"`
}

// EventMapResponse_Items_Item defines model for EventMapResponse.items.Item.
type EventMapResponse_Items_Item struct {
	union json.RawMessage
}

// EventSearchResponse defines model for EventSearchResponse.
type EventSearchResponse struct {
	AppliedFilters map[string]interface{}    `json:"applied_filters"`
	Items          []EventCard               `json:"items"`
	NextCursor     nullable.Nullable[string] `json:"next_cursor"`
	TotalEstimate  int                       `json:"total_estimate"`
}

// GeoPoint defines model for GeoPoint.
type GeoPoint struct {
	// Lat Передавайте вместе с lng; используется только для расчёта расстояния
	Lat float32 `json:"lat"`

	// Lng Передавайте вместе с lat; координаты не используются для профилирования вне подбора
	Lng float32 `json:"lng"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Database   HealthResponseDatabase   `json:"database"`
	Migrations HealthResponseMigrations `json:"migrations"`
	Status     HealthResponseStatus     `json:"status"`
}

// HealthResponseDatabase defines model for HealthResponse.Database.
type HealthResponseDatabase string

// HealthResponseMigrations defines model for HealthResponse.Migrations.
type HealthResponseMigrations string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// HomeFeedResponse defines model for HomeFeedResponse.
type HomeFeedResponse struct {
	ActiveRoom  nullable.Nullable[RoomSummary] `json:"active_room,omitempty"`
	FeedId      openapi_types.UUID             `json:"feed_id"`
	GeneratedAt time.Time                      `json:"generated_at"`
	Sections    []struct {
		Items []EventCard                  `json:"items"`
		Title string                       `json:"title"`
		Type  HomeFeedResponseSectionsType `json:"type"`
	} `json:"sections"`
}

// HomeFeedResponseSectionsType defines model for HomeFeedResponse.Sections.Type.
type HomeFeedResponseSectionsType string

// InviteContext defines model for InviteContext.
type InviteContext struct {
	AlreadyJoined bool                `json:"already_joined"`
	ExpiresAt     time.Time           `json:"expires_at"`
	Inviter       PublicParticipant   `json:"inviter"`
	RoomId        openapi_types.UUID  `json:"room_id"`
	RoomName      string              `json:"room_name"`
	Status        InviteContextStatus `json:"status"`
	Token         string              `json:"token"`
}

// InviteContextStatus defines model for InviteContext.Status.
type InviteContextStatus string

// Match defines model for Match.
type Match struct {
	Event        EventCard           `json:"event"`
	Id           openapi_types.UUID  `json:"id"`
	MatchedAt    time.Time           `json:"matched_at"`
	Participants []PublicParticipant `json:"participants"`
}

// MatchSummary defines model for MatchSummary.
type MatchSummary struct {
	EventId   openapi_types.UUID `json:"event_id"`
	Id        openapi_types.UUID `json:"id"`
	MatchedAt time.Time          `json:"matched_at"`

	// Participants Только безопасные display_name/avatar/role; MAX ID и intent не раскрываются
	Participants []PublicParticipant `json:"participants"`
	RoomId       openapi_types.UUID  `json:"room_id"`
}

// MyIntent defines model for MyIntent.
type MyIntent struct {
	BudgetMaxMinor int                  `json:"budget_max_minor"`
	CategorySlugs  []CategorySlug       `json:"category_slugs"`
	Dates          []openapi_types.Date `json:"dates"`

	// DayTypes Пустой массив означает любой день; значения объединяются OR
	DayTypes       []DayType                 `json:"day_types"`
	ExclusionSlugs []MyIntentExclusionSlugs  `json:"exclusion_slugs"`
	FreeText       nullable.Nullable[string] `json:"free_text,omitempty"`

	// Location При наличии radius задаёт origin; null с radius означает центр room city. Координаты не сохраняются дольше необходимого ranking
	Location nullable.Nullable[GeoPoint] `json:"location,omitempty"`

	// RadiusM null означает отсутствие distance filter; с location считается от координат, без location — от центра room city
	RadiusM     nullable.Nullable[int] `json:"radius_m,omitempty"`
	RoundNo     int                    `json:"round_no"`
	SubmittedAt time.Time              `json:"submitted_at"`

	// TimeSlots Пустой массив означает любое время; значения объединяются OR
	TimeSlots []TimeSlot `json:"time_slots"`
	Version   int        `json:"version"`
}

// MyIntentExclusionSlugs defines model for MyIntent.ExclusionSlugs.
type MyIntentExclusionSlugs string

// PoolSummary defines model for PoolSummary.
type PoolSummary struct {
	// ExhaustionReasons Только агрегированные причины без чужих данных
	ExhaustionReasons *[]struct {
		Code PoolSummaryExhaustionReasonsCode `json:"code"`
		Text string                           `json:"text"`
	} `json:"exhaustion_reasons,omitempty"`

	// IsSmall true, если в pool только 1–2 доступных события
	IsSmall bool `json:"is_small"`

	// MyPoolFinished Текущий участник проголосовал по всем доступным карточкам
	MyPoolFinished    bool                   `json:"my_pool_finished"`
	RetryAfterSeconds nullable.Nullable[int] `json:"retry_after_seconds,omitempty"`

	// RoomExhausted Оба участника завершили текущий pool без match
	RoomExhausted bool             `json:"room_exhausted"`
	RoundNo       int              `json:"round_no"`
	State         PoolSummaryState `json:"state"`
	Total         int              `json:"total"`
	Version       int              `json:"version"`
	VotedByMe     int              `json:"voted_by_me"`
}

// PoolSummaryExhaustionReasonsCode defines model for PoolSummary.ExhaustionReasons.Code.
type PoolSummaryExhaustionReasonsCode string

// PoolSummaryState defines model for PoolSummary.State.
type PoolSummaryState string

// PreferencesRequest defines model for PreferencesRequest.
type PreferencesRequest struct {
	BudgetMaxMinor int                `json:"budget_max_minor"`
	CityId         openapi_types.UUID `json:"city_id"`
	InterestSlugs  []CategorySlug     `json:"interest_slugs"`
	UsualDayTypes  []DayType          `json:"usual_day_types"`
	UsualTimeSlots []TimeSlot         `json:"usual_time_slots"`
}

// PreferencesResponse defines model for PreferencesResponse.
type PreferencesResponse struct {
	BudgetMaxMinor int                `json:"budget_max_minor"`
	CityId         openapi_types.UUID `json:"city_id"`
	InterestSlugs  []CategorySlug     `json:"interest_slugs"`
	UpdatedAt      time.Time          `json:"updated_at"`
	UsualDayTypes  []DayType          `json:"usual_day_types"`
	UsualTimeSlots []TimeSlot         `json:"usual_time_slots"`
	Version        int                `json:"version"`
}

// PublicParticipant defines model for PublicParticipant.
type PublicParticipant struct {
	AvatarUrl   nullable.Nullable[string] `json:"avatar_url,omitempty"`
	DisplayName string                    `json:"display_name"`
	Id          openapi_types.UUID        `json:"id"`

	// IntentReady Подтверждение intent для текущего round; не раскрывает содержимое intent
	IntentReady bool                  `json:"intent_ready"`
	Role        PublicParticipantRole `json:"role"`
}

// PublicParticipantRole defines model for PublicParticipant.Role.
type PublicParticipantRole string

// RecommendationReason defines model for RecommendationReason.
type RecommendationReason struct {
	Code RecommendationReasonCode `json:"code"`
	Text string                   `json:"text"`
}

// RecommendationReasonCode defines model for RecommendationReason.Code.
type RecommendationReasonCode string

// RoomEventsResponse defines model for RoomEventsResponse.
type RoomEventsResponse struct {
	Items []struct {
		// Cursor Opaque pagination cursor; не передаётся в vote
		Cursor   string    `json:"cursor"`
		Event    EventCard `json:"event"`
		Position int       `json:"position"`
	} `json:"items"`
	NextCursor  nullable.Nullable[string] `json:"next_cursor"`
	PoolVersion int                       `json:"pool_version"`
	RoomId      openapi_types.UUID        `json:"room_id"`
	RoundNo     int                       `json:"round_no"`
	Total       int                       `json:"total"`
}

// RoomIntentRequest defines model for RoomIntentRequest.
type RoomIntentRequest struct {
	BudgetMaxMinor int                  `json:"budget_max_minor"`
	CategorySlugs  []CategorySlug       `json:"category_slugs"`
	Dates          []openapi_types.Date `json:"dates"`

	// DayTypes Пустой массив означает любой день; значения объединяются OR
	DayTypes       []DayType                         `json:"day_types"`
	ExclusionSlugs []RoomIntentRequestExclusionSlugs `json:"exclusion_slugs"`
	FreeText       nullable.Nullable[string]         `json:"free_text,omitempty"`

	// Location При наличии radius задаёт origin; null с radius означает центр room city. Координаты не сохраняются дольше необходимого ranking
	Location nullable.Nullable[GeoPoint] `json:"location,omitempty"`

	// RadiusM null означает отсутствие distance filter; с location считается от координат, без location — от центра room city
	RadiusM nullable.Nullable[int] `json:"radius_m,omitempty"`

	// TimeSlots Пустой массив означает любое время; значения объединяются OR
	TimeSlots []TimeSlot `json:"time_slots"`
}

// RoomIntentRequestExclusionSlugs defines model for RoomIntentRequest.ExclusionSlugs.
type RoomIntentRequestExclusionSlugs string

// RoomInvite defines model for RoomInvite.
type RoomInvite struct {
	ExpiresAt   time.Time `json:"expires_at"`
	MaxDeepLink string    `json:"max_deep_link"`
	Url         string    `json:"url"`
}

// RoomSnapshot defines model for RoomSnapshot.
type RoomSnapshot struct {
	AllowedActions []RoomSnapshotAllowedActions `json:"allowed_actions"`
	CityId         openapi_types.UUID           `json:"city_id"`
	CreatedAt      time.Time                    `json:"created_at"`

	// ExpiresAt Invite и room истекают через 48 часов
	ExpiresAt time.Time          `json:"expires_at"`
	Id        openapi_types.UUID `json:"id"`

	// Invite Только creator; null для participant
	Invite       nullable.Nullable[RoomInvite]   `json:"invite"`
	Match        nullable.Nullable[MatchSummary] `json:"match"`
	MyIntent     nullable.Nullable[MyIntent]     `json:"my_intent"`
	Name         string                          `json:"name"`
	Participants []PublicParticipant             `json:"participants"`
	Pool         nullable.Nullable[PoolSummary]  `json:"pool"`

	// RoundNo Текущий round подтверждения intent и построения pool
	RoundNo int       `json:"round_no"`
	State   RoomState `json:"state"`
	Version int       `json:"version"`
}

// RoomSnapshotAllowedActions defines model for RoomSnapshot.AllowedActions.
type RoomSnapshotAllowedActions string

// RoomState defines model for RoomState.
type RoomState string

// RoomSummary defines model for RoomSummary.
type RoomSummary struct {
	CityId openapi_types.UUID `json:"city_id"`
	Id     openapi_types.UUID `json:"id"`
	Name   string             `json:"name"`
	State  RoomState          `json:"state"`
}

// SavedEventsResponse defines model for SavedEventsResponse.
type SavedEventsResponse struct {
	Items []struct {
		Event   EventCard                       `json:"event"`
		Match   nullable.Nullable[MatchSummary] `json:"match,omitempty"`
		SavedAt nullable.Nullable[time.Time]    `json:"saved_at,omitempty"`
	} `json:"items"`
	NextCursor nullable.Nullable[string] `json:"next_cursor"`
}

// SavedStateResponse defines model for SavedStateResponse.
type SavedStateResponse struct {
	EventId openapi_types.UUID           `json:"event_id"`
	Saved   bool                         `json:"saved"`
	SavedAt nullable.Nullable[time.Time] `json:"saved_at"`
}

// TicketClickRequest defines model for TicketClickRequest.
type TicketClickRequest struct {
	RoomId nullable.Nullable[openapi_types.UUID] `json:"room_id,omitempty"`
	Source TicketClickRequestSource              `json:"source"`
}

// TicketClickRequestSource defines model for TicketClickRequest.Source.
type TicketClickRequestSource string

// TicketClickResponse defines model for TicketClickResponse.
type TicketClickResponse struct {
	// ExternalUrl Внешний HTTPS URL провайдера из allowlist; не является внутренним redirect или временным токеном
	ExternalUrl string `json:"external_url"`
}

// TimeSlot defines model for TimeSlot.
type TimeSlot string

// User defines model for User.
type User struct {
	AvatarUrl   nullable.Nullable[string]             `json:"avatar_url,omitempty"`
	CityId      nullable.Nullable[openapi_types.UUID] `json:"city_id,omitempty"`
	DisplayName string                                `json:"display_name"`
	Id          openapi_types.UUID                    `json:"id"`
	Locale      string                                `json:"locale"`
}

// Venue defines model for Venue.
type Venue struct {
	Address   string                     `json:"address"`
	District  nullable.Nullable[string]  `json:"district,omitempty"`
	Id        openapi_types.UUID         `json:"id"`
	Latitude  nullable.Nullable[float32] `json:"latitude,omitempty"`
	Longitude nullable.Nullable[float32] `json:"longitude,omitempty"`
	Metro     nullable.Nullable[string]  `json:"metro,omitempty"`
	Name      string                     `json:"name"`
}

// VoteRequest defines model for VoteRequest.
type VoteRequest struct {
	PoolVersion int       `json:"pool_version"`
	Vote        VoteValue `json:"vote"`
}

// VoteResponse defines model for VoteResponse.
type VoteResponse struct {
	AcceptedVote   VoteValue                `json:"accepted_vote"`
	Match          nullable.Nullable[Match] `json:"match"`
	MyPoolFinished bool                     `json:"my_pool_finished"`
	PoolVersion    int                      `json:"pool_version"`
	RoomExhausted  bool                     `json:"room_exhausted"`
}

// VoteValue defines model for VoteValue.
type VoteValue string

// CityId defines model for CityId.
type CityId = openapi_types.UUID

// Cursor defines model for Cursor.
type Cursor = string

// EventId defines model for EventId.
type EventId = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Limit defines model for Limit.
type Limit = int

// RoomId defines model for RoomId.
type RoomId = openapi_types.UUID

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// RateLimited defines model for RateLimited.
type RateLimited = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ErrorResponse

// GetEventMapParams defines parameters for GetEventMap.
type GetEventMapParams struct {
	// CityId Город каталога. Если не передан, backend использует city_id из профиля пользователя; если его нет — VALIDATION_FAILED.
	CityId        *CityId             `form:"city_id,omitempty" json:"city_id,omitempty"`
	West          float32             `form:"west" json:"west"`
	South         float32             `form:"south" json:"south"`
	East          float32             `form:"east" json:"east"`
	North         float32             `form:"north" json:"north"`
	Zoom          int                 `form:"zoom" json:"zoom"`
	Q             *string             `form:"q,omitempty" json:"q,omitempty"`
	DateFrom      *openapi_types.Date `form:"date_from,omitempty" json:"date_from,omitempty"`
	DateTo        *openapi_types.Date `form:"date_to,omitempty" json:"date_to,omitempty"`
	DayTypes      *[]DayType          `form:"day_types,omitempty" json:"day_types,omitempty"`
	TimeSlots     *[]TimeSlot         `form:"time_slots,omitempty" json:"time_slots,omitempty"`
	CategorySlugs *[]CategorySlug     `form:"category_slugs,omitempty" json:"category_slugs,omitempty"`
	PriceMaxMinor *int                `form:"price_max_minor,omitempty" json:"price_max_minor,omitempty"`
	DistanceM     *int                `form:"distance_m,omitempty" json:"distance_m,omitempty"`
	Lat           *float32            `form:"lat,omitempty" json:"lat,omitempty"`
	Lng           *float32            `form:"lng,omitempty" json:"lng,omitempty"`
	FreeOnly      *bool               `form:"free_only,omitempty" json:"free_only,omitempty"`
}

// SearchEventsParams defines parameters for SearchEvents.
type SearchEventsParams struct {
	// Q Поиск по названию, описанию и площадке
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// CityId Город каталога. Если не передан, backend использует city_id из профиля пользователя; если его нет — VALIDATION_FAILED.
	CityId   *CityId             `form:"city_id,omitempty" json:"city_id,omitempty"`
	DateFrom *openapi_types.Date `form:"date_from,omitempty" json:"date_from,omitempty"`
	DateTo   *openapi_types.Date `form:"date_to,omitempty" json:"date_to,omitempty"`

	// DayTypes Значения внутри массива объединяются OR; вместе с time_slots применяется AND
	DayTypes      *[]DayType      `form:"day_types,omitempty" json:"day_types,omitempty"`
	TimeSlots     *[]TimeSlot     `form:"time_slots,omitempty" json:"time_slots,omitempty"`
	CategorySlugs *[]CategorySlug `form:"category_slugs,omitempty" json:"category_slugs,omitempty"`
	PriceMaxMinor *int            `form:"price_max_minor,omitempty" json:"price_max_minor,omitempty"`

	// DistanceM Требует одновременно lat и lng; без пары координат API возвращает VALIDATION_FAILED
	DistanceM *int     `form:"distance_m,omitempty" json:"distance_m,omitempty"`
	Lat       *float32 `form:"lat,omitempty" json:"lat,omitempty"`
	Lng       *float32 `form:"lng,omitempty" json:"lng,omitempty"`
	FreeOnly  *bool    `form:"free_only,omitempty" json:"free_only,omitempty"`
	West      *float32 `form:"west,omitempty" json:"west,omitempty"`
	South     *float32 `form:"south,omitempty" json:"south,omitempty"`
	East      *float32 `form:"east,omitempty" json:"east,omitempty"`
	North     *float32 `form:"north,omitempty" json:"north,omitempty"`
	Limit     *Limit   `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque подписанный cursor
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetHomeFeedParams defines parameters for GetHomeFeed.
type GetHomeFeedParams struct {
	// CityId Город каталога. Если не передан, backend использует city_id из профиля пользователя; если его нет — VALIDATION_FAILED.
	CityId *CityId `form:"city_id,omitempty" json:"city_id,omitempty"`

	// Lat Необязательная координата для секции nearby; передаётся только вместе с lng и после согласия пользователя
	Lat *float32 `form:"lat,omitempty" json:"lat,omitempty"`

	// Lng Необязательная координата для секции nearby; передаётся только вместе с lat и после согласия пользователя
	Lng   *float32 `form:"lng,omitempty" json:"lng,omitempty"`
	Limit *Limit   `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetInternalAnalyticsDashboardParams defines parameters for GetInternalAnalyticsDashboard.
type GetInternalAnalyticsDashboardParams struct {
	// Days Размер дневного окна; каталог качества и некоторые защитные метрики являются текущим срезом.
	Days *GetInternalAnalyticsDashboardParamsDays `form:"days,omitempty" json:"days,omitempty"`
}

// GetInternalAnalyticsDashboardParamsDays defines parameters for GetInternalAnalyticsDashboard.
type GetInternalAnalyticsDashboardParamsDays int

// GetMySavedEventsParams defines parameters for GetMySavedEvents.
type GetMySavedEventsParams struct {
	Tab   *GetMySavedEventsParamsTab `form:"tab,omitempty" json:"tab,omitempty"`
	Limit *Limit                     `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque подписанный cursor
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetMySavedEventsParamsTab defines parameters for GetMySavedEvents.
type GetMySavedEventsParamsTab string

// SetSavedEventJSONBody defines parameters for SetSavedEvent.
type SetSavedEventJSONBody struct {
	Saved bool `json:"saved"`
}

// JoinRoomByInviteParams defines parameters for JoinRoomByInvite.
type JoinRoomByInviteParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateRoomParams defines parameters for CreateRoom.
type CreateRoomParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetRoomEventsParams defines parameters for GetRoomEvents.
type GetRoomEventsParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque подписанный cursor
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// BootstrapMaxSessionJSONRequestBody defines body for BootstrapMaxSession for application/json ContentType.
type BootstrapMaxSessionJSONRequestBody = BootstrapRequest

// IngestBehaviorEventsJSONRequestBody defines body for IngestBehaviorEvents for application/json ContentType.
type IngestBehaviorEventsJSONRequestBody = BehaviorBatchRequest

// RecordTicketClickJSONRequestBody defines body for RecordTicketClick for application/json ContentType.
type RecordTicketClickJSONRequestBody = TicketClickRequest

// ReplaceMyPreferencesJSONRequestBody defines body for ReplaceMyPreferences for application/json ContentType.
type ReplaceMyPreferencesJSONRequestBody = PreferencesRequest

// SetSavedEventJSONRequestBody defines body for SetSavedEvent for application/json ContentType.
type SetSavedEventJSONRequestBody SetSavedEventJSONBody

// CreateRoomJSONRequestBody defines body for CreateRoom for application/json ContentType.
type CreateRoomJSONRequestBody = CreateRoomRequest

// VoteForRoomEventJSONRequestBody defines body for VoteForRoomEvent for application/json ContentType.
type VoteForRoomEventJSONRequestBody = VoteRequest

// ReplaceMyRoomIntentJSONRequestBody defines body for ReplaceMyRoomIntent for application/json ContentType.
type ReplaceMyRoomIntentJSONRequestBody = RoomIntentRequest

// Getter for additional properties for ErrorResponse_Error_Details. Returns the specified
// element and whether it was found
func (a ErrorResponse_Error_Details) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ErrorResponse_Error_Details
func (a *ErrorResponse_Error_Details) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ErrorResponse_Error_Details to handle AdditionalProperties
func (a *ErrorResponse_Error_Details) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["active_room"]; found {
		err = json.Unmarshal(raw, &a.ActiveRoom)
		if err != nil {
			return fmt.Errorf("error reading 'active_room': %w", err)
		}
		delete(object, "active_room")
	}

	if raw, found := object["current_pool_version"]; found {
		err = json.Unmarshal(raw, &a.CurrentPoolVersion)
		if err != nil {
			return fmt.Errorf("error reading 'current_pool_version': %w", err)
		}
		delete(object, "current_pool_version")
	}

	if raw, found := object["field"]; found {
		err = json.Unmarshal(raw, &a.Field)
		if err != nil {
			return fmt.Errorf("error reading 'field': %w", err)
		}
		delete(object, "field")
	}

	if raw, found := object["fields"]; found {
		err = json.Unmarshal(raw, &a.Fields)
		if err != nil {
			return fmt.Errorf("error reading 'fields': %w", err)
		}
		delete(object, "fields")
	}

	if raw, found := object["match"]; found {
		err = json.Unmarshal(raw, &a.Match)
		if err != nil {
			return fmt.Errorf("error reading 'match': %w", err)
		}
		delete(object, "match")
	}

	if raw, found := object["my_pool_finished"]; found {
		err = json.Unmarshal(raw, &a.MyPoolFinished)
		if err != nil {
			return fmt.Errorf("error reading 'my_pool_finished': %w", err)
		}
		delete(object, "my_pool_finished")
	}

	if raw, found := object["room_exhausted"]; found {
		err = json.Unmarshal(raw, &a.RoomExhausted)
		if err != nil {
			return fmt.Errorf("error reading 'room_exhausted': %w", err)
		}
		delete(object, "room_exhausted")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ErrorResponse_Error_Details to handle AdditionalProperties
func (a ErrorResponse_Error_Details) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ActiveRoom != nil {
		object["active_room"], err = json.Marshal(a.ActiveRoom)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'active_room': %w", err)
		}
	}

	if a.CurrentPoolVersion != nil {
		object["current_pool_version"], err = json.Marshal(a.CurrentPoolVersion)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'current_pool_version': %w", err)
		}
	}

	if a.Field != nil {
		object["field"], err = json.Marshal(a.Field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'field': %w", err)
		}
	}

	if a.Fields != nil {
		object["fields"], err = json.Marshal(a.Fields)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fields': %w", err)
		}
	}

	if a.Match != nil {
		object["match"], err = json.Marshal(a.Match)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'match': %w", err)
		}
	}

	if a.MyPoolFinished != nil {
		object["my_pool_finished"], err = json.Marshal(a.MyPoolFinished)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'my_pool_finished': %w", err)
		}
	}

	if a.RoomExhausted != nil {
		object["room_exhausted"], err = json.Marshal(a.RoomExhausted)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'room_exhausted': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsEventMapPoint returns the union data inside the EventMapResponse_Items_Item as a EventMapPoint
func (t EventMapResponse_Items_Item) AsEventMapPoint() (EventMapPoint, error) {
	var body EventMapPoint
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventMapPoint overwrites any union data inside the EventMapResponse_Items_Item as the provided EventMapPoint
func (t *EventMapResponse_Items_Item) FromEventMapPoint(v EventMapPoint) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventMapPoint performs a merge with any union data inside the EventMapResponse_Items_Item, using the provided EventMapPoint
func (t *EventMapResponse_Items_Item) MergeEventMapPoint(v EventMapPoint) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEventMapCluster returns the union data inside the EventMapResponse_Items_Item as a EventMapCluster
func (t EventMapResponse_Items_Item) AsEventMapCluster() (EventMapCluster, error) {
	var body EventMapCluster
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventMapCluster overwrites any union data inside the EventMapResponse_Items_Item as the provided EventMapCluster
func (t *EventMapResponse_Items_Item) FromEventMapCluster(v EventMapCluster) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventMapCluster performs a merge with any union data inside the EventMapResponse_Items_Item, using the provided EventMapCluster
func (t *EventMapResponse_Items_Item) MergeEventMapCluster(v EventMapCluster) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EventMapResponse_Items_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EventMapResponse_Items_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
